version: '2'
services:
  microservice:
    build: .
    image: gomicroservices:1.0.1-alpine
    environment:
    - PORT=9090
    ports:
    - "9090:9090"
  nginx:
    image: "nginx:latest"
    ports:
    - "8080:80"
    links:
    - microservice